"""init

Revision ID: 22a8786b15f2
Revises: 1aa040bd7f3b
Create Date: 2021-04-11 21:12:44.244749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22a8786b15f2'
down_revision = '1aa040bd7f3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
