"""init

Revision ID: 26116c934e1e
Revises: 22a8786b15f2
Create Date: 2021-04-11 21:28:29.632010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26116c934e1e'
down_revision = '22a8786b15f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('media_type', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo', 'media_type')
    # ### end Alembic commands ###
