"""init

Revision ID: 52a7f6155bb6
Revises: bc83e2033ae8
Create Date: 2021-05-02 22:43:23.767330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52a7f6155bb6'
down_revision = 'bc83e2033ae8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
