"""init

Revision ID: 547dd1f83cef
Revises: ccf4c219bd6c
Create Date: 2021-05-10 22:59:12.161680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '547dd1f83cef'
down_revision = 'ccf4c219bd6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_album_id'), 'album', ['id'], unique=False)
    op.create_table('album_to_photo',
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['album.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['photo_id'], ['photo.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('album_id', 'photo_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('album_to_photo')
    op.drop_index(op.f('ix_album_id'), table_name='album')
    op.drop_table('album')
    # ### end Alembic commands ###
