"""init

Revision ID: 6f2cc0df9e40
Revises: e79cb49f47ef
Create Date: 2021-03-14 22:14:47.892206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f2cc0df9e40'
down_revision = 'e79cb49f47ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('device_id', sa.String(length=256), nullable=False))
    op.add_column('photo', sa.Column('height', sa.Integer(), nullable=False))
    op.add_column('photo', sa.Column('latitude', sa.Float(), nullable=False))
    op.add_column('photo', sa.Column('longitude', sa.Float(), nullable=False))
    op.add_column('photo', sa.Column('modified_date', sa.DateTime(), nullable=False))
    op.add_column('photo', sa.Column('native_id', sa.String(length=256), nullable=False))
    op.add_column('photo', sa.Column('width', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo', 'width')
    op.drop_column('photo', 'native_id')
    op.drop_column('photo', 'modified_date')
    op.drop_column('photo', 'longitude')
    op.drop_column('photo', 'latitude')
    op.drop_column('photo', 'height')
    op.drop_column('photo', 'device_id')
    # ### end Alembic commands ###
