"""init

Revision ID: bc83e2033ae8
Revises: dc5e46f81451
Create Date: 2021-04-28 22:46:21.510418

"""
import sqlalchemy as sa
from alembic import op
# revision identifiers, used by Alembic.
from sqlalchemy import orm

from app.models.photo_model import Photo

revision = 'bc83e2033ae8'
down_revision = 'dc5e46f81451'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('file_size', sa.Float(), nullable=True))
    op.add_column('photo', sa.Column('thumbnail_file_size', sa.Float(), nullable=True))
    bind = op.get_bind()
    session = orm.Session(bind=bind)
    for photo in session.query(Photo):
        photo.file_size = 0.0
        photo.thumbnail_file_size = 0.0

    session.commit()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo', 'thumbnail_file_size')
    op.drop_column('photo', 'file_size')
    # ### end Alembic commands ###
