"""init

Revision ID: ccf4c219bd6c
Revises: 52a7f6155bb6
Create Date: 2021-05-02 22:50:38.377741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccf4c219bd6c'
down_revision = '52a7f6155bb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
