"""init

Revision ID: dc5e46f81451
Revises: 
Create Date: 2021-04-25 21:34:15.706795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc5e46f81451'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('native_id', sa.String(length=128), nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('checksum', sa.String(length=256), nullable=False),
    sa.Column('gphoto_id', sa.String(length=256), nullable=False),
    sa.Column('mime_type', sa.String(length=50), nullable=False),
    sa.Column('thumbnail_path', sa.String(length=1024), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_id'), 'photo', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photo_id'), table_name='photo')
    op.drop_table('photo')
    # ### end Alembic commands ###
