"""empty message

Revision ID: 1406b069ce17
Revises: 374550fd5828
Create Date: 2020-11-20 20:56:57.075366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1406b069ce17'
down_revision = '374550fd5828'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('checksum', sa.String(length=256), nullable=False),
    sa.Column('gphoto_id', sa.String(length=256), nullable=False),
    sa.Column('mime_type', sa.String(length=50), nullable=False),
    sa.Column('media_metadata', sa.JSON(none_as_null=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photos')
    # ### end Alembic commands ###
