"""empty message

Revision ID: 374550fd5828
Revises: 4aec2b9718f9
Create Date: 2020-11-19 22:25:38.150623

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '374550fd5828'
down_revision = '4aec2b9718f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photos',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('filename', sa.String(length=256), nullable=False),
                    sa.Column('checksum', sa.String(length=256), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photos')
    # ### end Alembic commands ###
