"""empty message

Revision ID: 4aec2b9718f9
Revises: 16c728dce0a5
Create Date: 2020-11-19 21:35:05.725994

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4aec2b9718f9'
down_revision = '16c728dce0a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photos',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('filename', sa.String(length=256), nullable=False),
                    sa.Column('checksum', sa.String(length=256), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photos')
    # ### end Alembic commands ###
