"""empty message

Revision ID: 63a0f82dc0b5
Revises: 7b14751bea34
Create Date: 2020-11-23 19:47:40.567286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63a0f82dc0b5'
down_revision = '7b14751bea34'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('thumbnail_path', sa.String(length=1024), nullable=False))
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'thumbnail_path')
    # ### end Alembic commands ###
