"""empty message

Revision ID: 7b14751bea34
Revises: 1406b069ce17
Create Date: 2020-11-22 20:49:04.864728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b14751bea34'
down_revision = '1406b069ce17'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('creation_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'creation_date')
    # ### end Alembic commands ###
