"""empty message

Revision ID: 9018d8ca8fb8
Revises: 
Create Date: 2021-01-22 22:59:20.851228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9018d8ca8fb8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('checksum', sa.String(length=256), nullable=False),
    sa.Column('gphoto_id', sa.String(length=256), nullable=False),
    sa.Column('mime_type', sa.String(length=50), nullable=False),
    sa.Column('media_metadata', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=1024), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photos')
    # ### end Alembic commands ###
