version: "3"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=photostore
    networks:
      dockernetwork:
        aliases:
          - "db.docker.local"
          - "db"

  web:
    build: .
    #    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    #    volumes:
    #      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

    networks:
      dockernetwork:
        aliases:
          - "web.docker.local"
          - "web"
networks:
  dockernetwork:
    driver: bridge

#  pgadmin:
#    container_name: pgadmin
#    image: dpage/pgadmin4
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
#      - PGADMIN_DEFAULT_PASSWORD=admin
#    ports:
#      - "5050:80"
#    depends_on:
#      - db