"""fff

Revision ID: 6655f87029ee
Revises: 3eed3c660474
Create Date: 2021-02-24 03:49:37.789443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6655f87029ee'
down_revision = '3eed3c660474'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
