
hiddenimports = [
    'fastapi',
    'fastapi.applications',
    'fastapi.datastructures',
    'fastapi.dependencies',
    'fastapi.dependencies.models',
    'fastapi.dependencies.utils',
    'fastapi.encoders',
    'fastapi.exception_handlers',
    'fastapi.exceptions',
    'fastapi.openapi',
    'fastapi.openapi.constants',
    'fastapi.openapi.docs',
    'fastapi.openapi.models',
    'fastapi.openapi.utils',
    'fastapi.param_functions',
    'fastapi.params',
    'fastapi.routing',
    'fastapi.security',
    'fastapi.security.api_key',
    'fastapi.security.base',
    'fastapi.security.http',
    'fastapi.security.oauth2',
    'fastapi.security.open_id_connect_url',
    'fastapi.security.utils',
    'fastapi.utils',
    ]