# hiddenimports = [
#     'uvicorn.config',
#     'uvicorn.importer',
#     'uvicorn.lifespan',
#     'uvicorn.lifespan.on',
#     'uvicorn.lifespan.off',
#     'uvicorn.loops',
#     'uvicorn.loops.asyncio',
#     'uvicorn.loops.auto',
#     'uvicorn.loops.uvloop',
#     'uvicorn.main',
#     'uvicorn.middleware',
#     'uvicorn.middleware.asgi2',
#     'uvicorn.middleware.debug',
#     'uvicorn.middleware.message_logger',
#     'uvicorn.middleware.proxy_headers',
#     'uvicorn.middleware.wsgi',
#     'uvicorn.protocols',
#     'uvicorn.protocols.http',
#     'uvicorn.protocols.http.auto',
#     'uvicorn.protocols.http.h11_impl',
#     'uvicorn.protocols.http.httptools_impl',
#     'uvicorn.protocols.utils',
#     'uvicorn.protocols.websockets',
#     'uvicorn.protocols.websockets.auto',
#     'uvicorn.protocols.websockets.websockets_impl',
#     'uvicorn.protocols.websockets.wsproto_impl',
#     'uvicorn.supervisors',
#     'uvicorn.supervisors.multiprocess',
#     'uvicorn.supervisors.statreload',
#     'uvicorn.workers']

from PyInstaller.utils.hooks import collect_submodules

hiddenimports = collect_submodules('uvicorn')